### ISSUE TITLE
How to share additional filters?

### ISSUE THREAD

**Issue by possibly** [sequitur/improv#1]
I made a new filter that I want to share with other people who end up using Improv. Should additional filters be merged into this repo via a pull request? Should I create a new npm module with the keywords #improv, #procjam? 

Specifically, I created a filter that works like `mismatchFilter` but inverted -- any group that has a tag which is mismatched against the model is INCLUDED. Groups without tags are included as well. I call it `mustMismatchFilter`.

**Comment by sequitur** [comment]
I'd rather not add things to the library itself unless they're broadly applicable or necessary for getting up to speed quickly, so I'd suggest you share these in a gist or a separate module on npm. If you make an npm module, I'd suggest these standards:
- Use `improv-filter` as an npm keyword
- Call it the module `mismatch-filter`; same name as the filter itself (`mismatchFilter`) but in kebab-case.
- Make sure the top-level export of your module is a function *that returns the filter itself,* a function, so that this works:

```javascript
const generator = new Improv(data, {
  filters: [require("mismatch-filter")()] // Note the function call parens at the end
};

// Or alternatively with ES6 imports:
import mismatchFilter from 'mismatch-filter';

const generator = new Improv(data, {
  filters: [mismatchFilter()]
};
```

The reason for this is that it's consistent with the built-in improv filters that have parameters to set their behavior when they're created. These are just suggestions but figuring out a consistent way of sharing Improv filters as npm modules might be useful in the future.

**Comment by nrkn** [comment]
Other projects dealing with the same issue often have a list of addons, extensions, complementary packages etc in the readme
